### ISSUE TITLE
Fix incidents on the same thread

### ISSUE THREAD

**Issue by ricardo-chaves-movile** [nzin/prometheus-cachethq#8]
Every time you have a fix for an incident, it opens a new incident, rather than fixing it on the same incident thread.

Wrong way:
![image](https://user-images.githubusercontent.com/43584809/59114054-b4fbc800-891c-11e9-9665-6a5d64b514ed.png)

Right way:
![image](https://user-images.githubusercontent.com/43584809/59114124-e1174900-891c-11e9-938f-f2b7f9af7605.png)

**Comment by tiago-cruz-movile** [comment]
I think that, instead of create a new incident, we should change the status to "fixed":

![image](https://user-images.githubusercontent.com/4048174/59121167-b84b7f80-892d-11e9-864f-e7baf4bacd6a.png)

```
 Investigating  ->  Identified ->   Watching ->   Fixed
```

Today the aplication does some like this:

- First: `Webhook DLR (delivery to handset) is facing issues`  status: `Identified `
- Second: `Webhook DLR (delivery to handset) services available` status: `Fixed`

So, the first became "Identified" forever, and we go some message in page: "Some systems are experiencing issues", even without any issues.

![image](https://user-images.githubusercontent.com/4048174/59121410-5ccdc180-892e-11e9-8094-eb19559436da.png)

**Comment by nzin** [comment]
Hi guys,
long time I didn't touch the code, I need to check. Maybe during next week

**Comment by sanjuicgithub** [comment]
> Hi guys,
> long time I didn't touch the code, I need to check. Maybe during next week

Hello @nzin , 
Can you please look into this issue once you return from your christmas and new year vacation ? :).  I have also got this requirement and would be great if you review and fix the code.

**Comment by nzin** [comment]
Hi guys,

sorry I forgot this one.
I am trying to do it (properly): https://github.com/nzin/prometheus-cachethq/pull/10

**Comment by nzin** [comment]
Hi @ricardo-chaves-movile ,

let's say I want to follow your workflow. How do you want to specify the time the service has been down?
I was wondering if I should write something like
```
The service is back online.
The service has been down for <hour-minute-seconds>
```

**Comment by sanjuicgithub** [comment]
@nzin , 
Today I tested your branch  'switchToGo113' and  doesn't look good to me. It's still creating the separate incident and not solving the incident on the same thread.  Can you please add your test case which you tested against this fix, want to ensure if i am missing something.

**Comment by nzin** [comment]
Hi @sanjuicgithub , I know I dont yet merge incidents.

To do so  I was asking a question: "let's say I want to follow your workflow. How do you want to specify the time the service has been down?
I was wondering if I should write something like..."

So I needed your input on it before solving it!

Regards,

**Comment by sanjuicgithub** [comment]
@nzin , 
I think, we should just go with the following message. 
               "The service is back online" 

Regards,
Sanjay.

**Comment by sanjuicgithub** [comment]
@nzin , May I know the expected date for this fix ?.

**Comment by nzin** [comment]
> @nzin , May I know the expected date for this fix ?.

Hi @sanjuicgithub , let me merge this PR, and then work on something corresponding to your need, but I want to put the outage range, so that not only we know it is fixed, but how long it was "down"

I will try to create a fix for the next week end.

**Comment by nzin** [comment]
Hi @sanjuicgithub , can you try docker image nzin/prometheus-cachethq:1.0.5
you need to set 2 env variables:
- SQUASH_INCIDENT="true"
- CACHETHQ_TIMEZONE="-0500" for EST, or -HHMM to match the timezone set in CachetHQ

**Comment by nzin** [comment]
I will try to make it simpler

**Comment by sanjuicgithub** [comment]
@nzin , 
Today I performed the test and observed the following : 

 If the Incident is created and resolved before the repeat_interval, it works fine , resolving on the same thread and everything works as expected, however when the same incident is repeated due to the repeat_interval, it still creates a new incident rather than updating the existing one and then it resolves only the last incident which was created and therefore the problem remained there due to the old incident.  Kindly see also the attachments(i have attached both 'without repeat_interval and with [repeat_interval'.](url
![Expected-result(without repeat_interval)](https://user-images.githubusercontent.com/41016780/73675143-32492980-46b2-11ea-8e85-23f0a004d21e.png)
![Unexpected-result(with repeat_interval)](https://user-images.githubusercontent.com/41016780/73675146-32e1c000-46b2-11ea-888c-5303c96d735a.png)

)

**Comment by nzin** [comment]
> @nzin ,
> Today I performed the test and observed the following :
> 
> If the Incident is created and resolved before the repeat_interval, it works fine , resolving on the same thread and everything works as expected, however when the same incident is repeated due to the repeat_interval, it still creates a new incident rather than updating the existing one and then it resolves only the last incident which was created and therefore the problem remained there due to the old incident. Kindly see also the attachments(i have attached both 'without repeat_interval and with [repeat_interval'.](url
> ![Expected-result(without repeat_interval)](https://user-images.githubusercontent.com/41016780/73675143-32492980-46b2-11ea-8e85-23f0a004d21e.png)
> ![Unexpected-result(with repeat_interval)](https://user-images.githubusercontent.com/41016780/73675146-32e1c000-46b2-11ea-888c-5303c96d735a.png)
> 
> )

Nice catch @sanjuicgithub .

can you try with nzin/prometheus-cachethq:1.0.6

btw, CACHETHQ_TIMEZONE is not required anymore. so just set "SQUASH_INCIDENT" to "true"

**Comment by sanjuicgithub** [comment]
@nzin , 

Everything looks good now. My special thanks to you for fixing this.

Regards,
Sanjay.

**Comment by nzin** [comment]
wonderful.

Let's close this ticket?
